name: Provision AWS EC2 Instance

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.9
    - name: Init Terraform
      run: terraform init
    - name: Apply Terraform
      id: apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Output SSH command
      run: echo "SSH command: ssh -i ${{ secrets.AWS_SSH_KEY_PATH }} ubuntu@${{ steps.apply.outputs.instance_public_ip }}"
