name: Ubuntu - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Downloading & Installing Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl python3 python3-pip
